// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: arena.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const InsertArena = `-- name: InsertArena :one
INSERT INTO arenas (
  arena_name,
  arena_email
)
VALUES (
  $1,
  $2
)
RETURNING arena_uuid
`

type InsertArenaParams struct {
	ArenaName  string
	ArenaEmail string
}

func (q *Queries) InsertArena(ctx context.Context, arg InsertArenaParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, InsertArena, arg.ArenaName, arg.ArenaEmail)
	var arena_uuid uuid.UUID
	err := row.Scan(&arena_uuid)
	return arena_uuid, err
}

const UpdateArena = `-- name: UpdateArena :one
UPDATE arenas SET
  arena_name = $1,
  arena_email = $2
WHERE arena_uuid = $3
RETURNING arena_uuid AS res
`

type UpdateArenaParams struct {
	ArenaName  string
	ArenaEmail string
	ArenaUuid  uuid.UUID
}

func (q *Queries) UpdateArena(ctx context.Context, arg UpdateArenaParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, UpdateArena, arg.ArenaName, arg.ArenaEmail, arg.ArenaUuid)
	var res uuid.UUID
	err := row.Scan(&res)
	return res, err
}
